-- MySQL Script generated by MySQL Workbench
-- Sun Nov 27 20:01:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET utf8 ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Persona` (
  `id` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `img` LONGTEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `prueba`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Estudio` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NOT NULL,
  `fecha` VARCHAR(10) NOT NULL,
  `descripción` LONGTEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  UNIQUE INDEX `fecha_UNIQUE` (`fecha` ASC) ,
  INDEX `fk_Estudio_Persona_idx` (`Persona_id` ASC) ,
  CONSTRAINT `fk_Estudio_Persona`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `prueba`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prueba`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Proyecto` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NOT NULL,
  `fecha` VARCHAR(10) NOT NULL,
  `descripción` LONGTEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `img` LONGTEXT NOT NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  UNIQUE INDEX `fecha_UNIQUE` (`fecha` ASC) ,
  INDEX `fk_Estudio_Persona_idx` (`Persona_id` ASC) ,
  CONSTRAINT `fk_Estudio_Persona0`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `prueba`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prueba`.`Experiencia_laboral_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Experiencia_laboral_copy1` (
  `id` INT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NOT NULL,
  `fecha` VARCHAR(10) NOT NULL,
  `descripción` LONGTEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  UNIQUE INDEX `fecha_UNIQUE` (`fecha` ASC) ,
  INDEX `fk_Estudio_Persona_idx` (`Persona_id` ASC) ,
  CONSTRAINT `fk_Estudio_Persona00`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `prueba`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prueba`.`Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`Habilidad` (
  `id` INT NULL AUTO_INCREMENT,
  `porcentaje` DECIMAL(2) NOT NULL,
  `titulo` VARCHAR(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Estudio_Persona_idx` (`Persona_id` ASC) ,
  CONSTRAINT `fk_Estudio_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `prueba`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
